### PR TITLE
Add new logical properties

### PR DESCRIPTION
**Pull request by Siilwyn**

### CODE REVIEW

**Comment by prantlf** [comment]
Thank you for starting with this so quickly! You covered all `border-block` properties. I tested your branch with my stylesheet and the `border-style` and `border-block-end` survived :-)

But this is just the beginning. Another group of the logical properties is `border-inline`. The pattern is just the same as `border-block`. Ant then there are fewer ones `margin-block` and `margin-inline`. And then there are others. They are nicely grouped at the [MDN documentation page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).

How would you deal with this? Gradually making this MR complete, or adding the properties with multiple MRs?

**Review by prantlf — APPROVED** [review]
All `border-block` properties, legible test.

**Comment by Siilwyn** [comment]
I'll push all needed new properties on this branch. To be honest I thought the safe sorting (`keepOverrides`) would be a feature just for legacy CSS that's why I didn't pay attention to these properties.

**Comment by Siilwyn** [comment]
@prantlf thanks for the linked MDN page was helpful to go through the properties on there. I'll probably merge this soon and publish a new version.

**Pull request merged**
